### ISSUE TITLE
Modal on tap

### ISSUE THREAD

**Issue by eavesr** [davedean/tdcm#13]
Maybe with full image name, last 50 lines of logs?
Button to pull latest version?

**Comment by eavesr** [comment]
Could move the image and remove buttons onto the modal so the main screen fits on your phone better?
They're likely things you'd be happy to drill in to access?

**Comment by davedean** [comment]
We've got a modal now, can add more stuff to it. Maybe time to send the whole container state direct to the front end, and then its easier to fiddle in react.
